# **Introduction**

Numpy is a multi-dimensional array library. Numpy is faster than lists which is the major reason why it is used. It is fast because it uses fixed types. Also, there is no type checking in Numpy and uses contiguous memory so numpy can use the SIMD (Single Instruction, Multiple Data) Vector Processing Units for faster calculation.

In [73]:
import numpy as np

In [74]:
a =  np.array([1,2,3], dtype="int32")
a

array([1, 2, 3], dtype=int32)

In [75]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [76]:
# get Dimensions
a.ndim

1

In [77]:
# get shape
b.shape

(2, 3)

In [78]:
# get type
a.dtype

dtype('int32')

In [79]:
# get size (bytes)
a.itemsize

4

In [80]:
# get size (number of elements)
a.size

3

In [81]:
# get total size
# a.size * a.itemsize
a.nbytes

12

# **Accessing / Changing specific elements, rows, columns, etc**

In [82]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [83]:
# getting specific element
a[1,5]

13

In [84]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [85]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [86]:
# [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [87]:
# 3-dimensions
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [88]:
# getting the 4
b[0,1,1]

4

# **Initializing different arrays**

In [89]:
# all 0's matrix
np.zeros(5) # this takes a shape which is a tuple

array([0., 0., 0., 0., 0.])

In [90]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [91]:
# all 1's of 32 bit
np.ones((4,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [92]:
# any other number
np.full((3,2,1), 99, dtype="float32")

array([[[99.],
        [99.]],

       [[99.],
        [99.]],

       [[99.],
        [99.]]], dtype=float32)

In [93]:
# copies shape from another np array
np.full_like(a, 2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [94]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [95]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [96]:
# random decimal numbers
np.random.rand(4,2)

array([[0.14315797, 0.55498435],
       [0.68432887, 0.76903023],
       [0.72338966, 0.23588543],
       [0.99731164, 0.29427887]])

In [98]:
# random decimal numbers based on another np array
np.random.random_sample(a.shape)

array([[0.49543639, 0.77018082, 0.01409409, 0.16504553, 0.37656809,
        0.31118214, 0.30591794],
       [0.52296476, 0.50087059, 0.40370761, 0.49876518, 0.73295756,
        0.54477213, 0.28009434]])

In [104]:
# random int values
np.random.randint(1,5, size=(3,3))

array([[1, 1, 1],
       [2, 2, 2],
       [2, 1, 4]])

In [106]:
# identity matrix
np.identity(3, dtype="int8")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [110]:
# repeat the array
np.repeat(a,3,axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [111]:
# when copying np arrays only the reference is changed, so we use copy()
b = a.copy()
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

# **Linear Algebra**

In [113]:
a = np.ones((2,3))
print("a=",a)

b = np.full((3,2),2)
print("b=",b)

np.matmul(a,b)

a= [[1. 1. 1.]
 [1. 1. 1.]]
b= [[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [118]:
c = np.identity(3)

In [116]:
# determinant
np.linalg.det(c)

1.0

In [119]:
# eigen values and eigen vectors
np.linalg.eig(c) #  returns the eigenvalues and right vectors of a square array

(array([1., 1., 1.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [120]:
# eigen values
np.linalg.eigvals(c)

array([1., 1., 1.])

In [121]:
# inverse of a matrix
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
# dot product
np.dot(c,a.T)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# **Statistics**

In [124]:
a.min()

1.0

In [131]:
a.max(axis=1)

array([1., 1.])

In [126]:
a.std()

0.0

In [130]:
a.argmin()

0

In [132]:
a.mean()

1.0

In [133]:
a.sum()

6.0

# **Reorganize Arrays**

In [135]:
# reshape
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [138]:
# stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]))
print(np.hstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
