In [5]:
import numpy as np

#**Numpy Arrays**

In [11]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros(((3,4,5))) # number of brackets => dimension of array

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [18]:
np.ones((3,3))  # number of brackets => dimension of array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(10,20,5) # returns evenly spaced numbers over a specified interval (linearly spaced)

array([10. , 12.5, 15. , 17.5, 20. ])

In [22]:
np.eye(5) # returns an identity array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(1) # returns uniform distribution of random numbers from [0,1)

array([0.69193719])

In [25]:
np.random.rand(5,5) # returns an array of uniform distribution of random numbers from [0,1)

array([[0.5155419 , 0.64049267, 0.39679476, 0.51422674, 0.71586852],
       [0.8127513 , 0.82717104, 0.76455942, 0.07272749, 0.62710288],
       [0.1175737 , 0.73301753, 0.74937381, 0.01548133, 0.51350835],
       [0.77032198, 0.23173865, 0.82173037, 0.27769186, 0.19551427],
       [0.5238603 , 0.1709044 , 0.99410124, 0.0986928 , 0.46268193]])

In [31]:
np.random.randn(5)  # returns standard normal distribution (also known as Gaussian distribution where mean is 0 and variance is 1) of random numbers centered at 0 and variance is 1

array([ 0.98854197,  0.56740792,  0.13542029, -1.19380464,  0.64903951])

In [33]:
np.random.randint(1, 100, 10) # returns random integer

array([70, 63, 24, 48, 40, 73, 82,  4, 50, 49])

In [37]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[16 33 10 17 41 17 23 24  9 25]


In [38]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(25,)

In [42]:
arr.reshape(5,5).shape

(5, 5)

In [44]:
arr.dtype

dtype('int64')

In [45]:
ranarr.max()

41

In [47]:
ranarr.min()

9

In [46]:
ranarr.argmax()

4

In [48]:
ranarr.argmin()

8

#**Numpy Operations**

In [49]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [52]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [54]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [55]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [56]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [57]:
np.max(arr)

9

In [58]:
np.argmax(arr)

9

In [62]:
np.min(arr)

0

In [60]:
np.argmin(arr)

0

In [64]:
np.arctan(arr)

array([0.        , 0.78539816, 1.10714872, 1.24904577, 1.32581766,
       1.37340077, 1.40564765, 1.42889927, 1.44644133, 1.46013911])

In [65]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#**Numpy Indexing and Selection**

In [71]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [72]:
arr[1]

1

In [73]:
arr[:2]

array([0, 1])

In [74]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[-3:-1]

array([8, 9])

In [82]:
arr[0:5] = 100  # brodcasting
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [83]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [84]:
slice_of_arr = arr[:6]  # this is a pointer to the actual array
print(slice_of_arr)

[0 1 2 3 4 5]


In [85]:
slice_of_arr[:] = 99
print(slice_of_arr)

[99 99 99 99 99 99]


In [86]:
print(arr) # as slice_of_array was a pointer

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [90]:
arr_copy = arr.copy()
arr_copy[:] = 200
print(arr_copy)

[200 200 200 200 200 200 200 200 200 200 200]


In [91]:
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]


In [93]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(mat)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [94]:
print(mat[0])

[ 5 10 15]


In [97]:
print(mat[1][1])

25


In [98]:
print(mat[1,1])

25


In [99]:
mat[:2,1:] # matrix slicing

array([[10, 15],
       [25, 30]])

In [100]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [101]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [103]:
bool_arr = arr > 4
print(arr[bool_arr])

[ 5  6  7  8  9 10]


In [105]:
print(arr[arr > 4])  # conditional selection

[ 5  6  7  8  9 10]
